### ISSUE TITLE
What do you think about this design?

### ISSUE THREAD

**Issue by jonicious** [jonicious/CSSclasses#3]
I changed the heading level from `h2` to `h3` for "Team" and "Coaches" and used `h2` for each city. What do you think?

**New design**

![New design](http://screenshots.jonas.re/X3tZUzMVAC.png)

**Current design**

![Current design](http://screenshots.jonas.re/sPTHwJfGxy.png)

**Comment by LeonardKoch** [comment]
Looks great!

**Comment by LeonardKoch** [comment]
![profilephoto_cropped](https://cloud.githubusercontent.com/assets/2767186/14059719/20b1677c-f34c-11e5-9574-13001b644014.png)
My profile picture for the about page.

**Comment by jonicious** [comment]
Under each city headline we may shortly tell some things about the meetup in this city in general, e.g. when it was first started and when the next meetup takes place. Probably there is a way to get this information via the meetup API.
